import { Card } from "@/types/Card";

export let CardBackImg = 'img/cards/green_back.png';

export let CardImgList = [
  'img/cards/10_of_clubs.png',
  'img/cards/10_of_diamonds.png',
  'img/cards/10_of_hearts.png',
  'img/cards/10_of_spades.png',
  'img/cards/2_of_clubs.png',
  'img/cards/2_of_diamonds.png',
  'img/cards/2_of_hearts.png',
  'img/cards/2_of_spades.png',
  'img/cards/3_of_clubs.png',
  'img/cards/3_of_diamonds.png',
  'img/cards/3_of_hearts.png',
  'img/cards/3_of_spades.png',
  'img/cards/4_of_clubs.png',
  'img/cards/4_of_diamonds.png',
  'img/cards/4_of_hearts.png',
  'img/cards/4_of_spades.png',
  'img/cards/5_of_clubs.png',
  'img/cards/5_of_diamonds.png',
  'img/cards/5_of_hearts.png',
  'img/cards/5_of_spades.png',
  'img/cards/6_of_clubs.png',
  'img/cards/6_of_diamonds.png',
  'img/cards/6_of_hearts.png',
  'img/cards/6_of_spades.png',
  'img/cards/7_of_clubs.png',
  'img/cards/7_of_diamonds.png',
  'img/cards/7_of_hearts.png',
  'img/cards/7_of_spades.png',
  'img/cards/8_of_clubs.png',
  'img/cards/8_of_diamonds.png',
  'img/cards/8_of_hearts.png',
  'img/cards/8_of_spades.png',
  'img/cards/9_of_clubs.png',
  'img/cards/9_of_diamonds.png',
  'img/cards/9_of_hearts.png',
  'img/cards/9_of_spades.png',
  'img/cards/ace_of_clubs.png',
  'img/cards/ace_of_diamonds.png',
  'img/cards/ace_of_hearts.png',
  'img/cards/ace_of_spades2.png',
  'img/cards/jack_of_clubs2.png',
  'img/cards/jack_of_diamonds2.png',
  'img/cards/jack_of_hearts2.png',
  'img/cards/jack_of_spades2.png',
  'img/cards/king_of_clubs2.png',
  'img/cards/king_of_diamonds2.png',
  'img/cards/king_of_hearts2.png',
  'img/cards/king_of_spades2.png',
  'img/cards/queen_of_clubs2.png',
  'img/cards/queen_of_diamonds2.png',
  'img/cards/queen_of_hearts2.png',
  'img/cards/queen_of_spades2.png',
  'img/cards/black_joker.png',
  'img/cards/red_joker.png',
];

export let CardsList: Card[] = [
  { pica: "tréboles", representation: "10", value: 10, img: "img/cards/10_of_clubs.png" },
  { pica: "diamantes", representation: "10", value: 10, img: "img/cards/10_of_diamonds.png" },
  { pica: "corazones", representation: "10", value: 10, img: "img/cards/10_of_hearts.png" },
  { pica: "picas", representation: "10", value: 10, img: "img/cards/10_of_spades.png" },
  { pica: "tréboles", representation: "2", value: 2, img: "img/cards/2_of_clubs.png" },
  { pica: "diamantes", representation: "2", value: 2, img: "img/cards/2_of_diamonds.png" },
  { pica: "corazones", representation: "2", value: 2, img: "img/cards/2_of_hearts.png" },
  { pica: "picas", representation: "2", value: 2, img: "img/cards/2_of_spades.png" },
  { pica: "tréboles", representation: "3", value: 3, img: "img/cards/3_of_clubs.png" },
  { pica: "diamantes", representation: "3", value: 3, img: "img/cards/3_of_diamonds.png" },
  { pica: "corazones", representation: "3", value: 3, img: "img/cards/3_of_hearts.png" },
  { pica: "picas", representation: "3", value: 3, img: "img/cards/3_of_spades.png" },
  { pica: "tréboles", representation: "4", value: 4, img: "img/cards/4_of_clubs.png" },
  { pica: "diamantes", representation: "4", value: 4, img: "img/cards/4_of_diamonds.png" },
  { pica: "corazones", representation: "4", value: 4, img: "img/cards/4_of_hearts.png" },
  { pica: "picas", representation: "4", value: 4, img: "img/cards/4_of_spades.png" },
  { pica: "tréboles", representation: "5", value: 5, img: "img/cards/5_of_clubs.png" },
  { pica: "diamantes", representation: "5", value: 5, img: "img/cards/5_of_diamonds.png" },
  { pica: "corazones", representation: "5", value: 5, img: "img/cards/5_of_hearts.png" },
  { pica: "picas", representation: "5", value: 5, img: "img/cards/5_of_spades.png" },
  { pica: "tréboles", representation: "6", value: 6, img: "img/cards/6_of_clubs.png" },
  { pica: "diamantes", representation: "6", value: 6, img: "img/cards/6_of_diamonds.png" },
  { pica: "corazones", representation: "6", value: 6, img: "img/cards/6_of_hearts.png" },
  { pica: "picas", representation: "6", value: 6, img: "img/cards/6_of_spades.png" },
  { pica: "tréboles", representation: "7", value: 7, img: "img/cards/7_of_clubs.png" },
  { pica: "diamantes", representation: "7", value: 7, img: "img/cards/7_of_diamonds.png" },
  { pica: "corazones", representation: "7", value: 7, img: "img/cards/7_of_hearts.png" },
  { pica: "picas", representation: "7", value: 7, img: "img/cards/7_of_spades.png" },
  { pica: "tréboles", representation: "8", value: 8, img: "img/cards/8_of_clubs.png" },
  { pica: "diamantes", representation: "8", value: 8, img: "img/cards/8_of_diamonds.png" },
  { pica: "corazones", representation: "8", value: 8, img: "img/cards/8_of_hearts.png" },
  { pica: "picas", representation: "8", value: 8, img: "img/cards/8_of_spades.png" },
  { pica: "tréboles", representation: "9", value: 9, img: "img/cards/9_of_clubs.png" },
  { pica: "diamantes", representation: "9", value: 9, img: "img/cards/9_of_diamonds.png" },
  { pica: "corazones", representation: "9", value: 9, img: "img/cards/9_of_hearts.png" },
  { pica: "picas", representation: "9", value: 9, img: "img/cards/9_of_spades.png" },
  { pica: "tréboles", representation: "As", value: 11, img: "img/cards/ace_of_clubs.png" },
  { pica: "diamantes", representation: "As", value: 11, img: "img/cards/ace_of_diamonds.png" },
  { pica: "corazones", representation: "As", value: 11, img: "img/cards/ace_of_hearts.png" },
  { pica: "picas", representation: "As", value: 11, img: "img/cards/ace_of_spades2.png" },
  { pica: "tréboles", representation: "Jota", value: 10, img: "img/cards/jack_of_clubs2.png" },
  { pica: "diamantes", representation: "Jota", value: 10, img: "img/cards/jack_of_diamonds2.png" },
  { pica: "corazones", representation: "Jota", value: 10, img: "img/cards/jack_of_hearts2.png" },
  { pica: "picas", representation: "Jota", value: 10, img: "img/cards/jack_of_spades2.png" },
  { pica: "tréboles", representation: "Rey", value: 10, img: "img/cards/king_of_clubs2.png" },
  { pica: "diamantes", representation: "Rey", value: 10, img: "img/cards/king_of_diamonds2.png" },
  { pica: "corazones", representation: "Rey", value: 10, img: "img/cards/king_of_hearts2.png" },
  { pica: "picas", representation: "Rey", value: 10, img: "img/cards/king_of_spades2.png" },
  { pica: "tréboles", representation: "Reina", value: 10, img: "img/cards/queen_of_clubs2.png" },
  { pica: "diamantes", representation: "Reina", value: 10, img: "img/cards/queen_of_diamonds2.png" },
  { pica: "corazones", representation: "Reina", value: 10, img: "img/cards/queen_of_hearts2.png" },
  { pica: "picas", representation: "Reina", value: 10, img: "img/cards/queen_of_spades2.png" },
  { pica: "comodín", representation: "Negro", value: -1, img: "img/cards/black_joker.png" },
  { pica: "comodín", representation: "Rojo", value: -1, img: "img/cards/red_joker.png" },
];
